weights: yolov5s6.pt
cfg: ''
data: /scratch/ichakr2s/bdd100k/data/bdd100k_10k_ins_seg_images_annotations_yolov5pytorch/bdd100k_10k_ins_seg_images_labels_train_val_test_yolov5pytorch/data.yaml
hyp: /home/ichakr2s/my_projects/BDD10-DA-Yolov5/BDD10-DA-Yolov5/yolov5/data/hyps/hyp.scratch-low.yaml
epochs: 300
batch_size: 16
imgsz: 1280
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp6
